// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgPatternDPColorSquare (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        y,
        x,
        color,
        dpDynamicRange,
        dpYUVCoef,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] y;
input  [15:0] x;
input  [7:0] color;
input  [7:0] dpDynamicRange;
input  [7:0] dpYUVCoef;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] vBarSel_1;
reg   [5:0] yCount_V_1;
reg   [2:0] hBarSel_1;
reg   [9:0] xCount_V_1;
wire   [3:0] DPtpgBarArray_address0;
reg    DPtpgBarArray_ce0;
wire   [2:0] DPtpgBarArray_q0;
wire   [2:0] DPtpgBarSelRgb_VESA_r_address0;
reg    DPtpgBarSelRgb_VESA_r_ce0;
wire   [1:0] DPtpgBarSelRgb_VESA_r_q0;
wire   [2:0] DPtpgBarSelRgb_VESA_g_address0;
reg    DPtpgBarSelRgb_VESA_g_ce0;
wire   [1:0] DPtpgBarSelRgb_VESA_g_q0;
wire   [2:0] DPtpgBarSelRgb_VESA_b_address0;
reg    DPtpgBarSelRgb_VESA_b_ce0;
wire   [1:0] DPtpgBarSelRgb_VESA_b_q0;
wire   [2:0] DPtpgBarSelRgb_CEA_r_address0;
reg    DPtpgBarSelRgb_CEA_r_ce0;
wire   [5:0] DPtpgBarSelRgb_CEA_r_q0;
wire   [2:0] DPtpgBarSelRgb_CEA_g_address0;
reg    DPtpgBarSelRgb_CEA_g_ce0;
wire   [5:0] DPtpgBarSelRgb_CEA_g_q0;
wire   [2:0] DPtpgBarSelRgb_CEA_b_address0;
reg    DPtpgBarSelRgb_CEA_b_ce0;
wire   [5:0] DPtpgBarSelRgb_CEA_b_q0;
wire   [2:0] DPtpgBarSelYuv_601_y_address0;
reg    DPtpgBarSelYuv_601_y_ce0;
wire   [7:0] DPtpgBarSelYuv_601_y_q0;
wire   [2:0] DPtpgBarSelYuv_601_v_address0;
reg    DPtpgBarSelYuv_601_v_ce0;
wire   [7:0] DPtpgBarSelYuv_601_v_q0;
wire   [2:0] DPtpgBarSelYuv_709_y_address0;
reg    DPtpgBarSelYuv_709_y_ce0;
wire   [7:0] DPtpgBarSelYuv_709_y_q0;
wire   [2:0] DPtpgBarSelYuv_709_v_address0;
reg    DPtpgBarSelYuv_709_v_ce0;
wire   [7:0] DPtpgBarSelYuv_709_v_q0;
wire   [2:0] DPtpgBarSelYuv_601_u_address0;
reg    DPtpgBarSelYuv_601_u_ce0;
wire   [7:0] DPtpgBarSelYuv_601_u_q0;
wire   [2:0] DPtpgBarSelYuv_709_u_address0;
reg    DPtpgBarSelYuv_709_u_ce0;
wire   [7:0] DPtpgBarSelYuv_709_u_q0;
wire   [0:0] icmp_ln1716_fu_313_p2;
reg   [0:0] icmp_ln1716_reg_747;
wire   [0:0] icmp_ln1716_1_fu_325_p2;
reg   [0:0] icmp_ln1716_1_reg_752;
wire   [0:0] cmp41_fu_337_p2;
wire   [0:0] cmp106_fu_343_p2;
wire   [0:0] and_ln1765_fu_361_p2;
reg   [0:0] and_ln1765_reg_769;
reg   [0:0] and_ln1765_reg_769_pp0_iter1_reg;
reg   [0:0] and_ln1765_reg_769_pp0_iter2_reg;
reg   [0:0] and_ln1765_reg_769_pp0_iter3_reg;
wire   [0:0] empty_60_fu_373_p2;
wire   [0:0] sel_tmp2_fu_379_p2;
wire   [0:0] xor_ln1728_fu_410_p2;
wire   [0:0] and_ln1721_fu_399_p2;
wire   [2:0] add_ln1745_fu_470_p2;
wire   [0:0] icmp_ln878_1_fu_452_p2;
reg   [1:0] DPtpgBarSelRgb_VESA_r_load_reg_880;
reg   [1:0] DPtpgBarSelRgb_VESA_g_load_reg_885;
reg   [1:0] DPtpgBarSelRgb_VESA_b_load_reg_890;
reg   [7:0] DPtpgBarSelYuv_709_y_load_reg_895;
reg   [7:0] DPtpgBarSelYuv_709_v_load_reg_900;
reg   [7:0] DPtpgBarSelYuv_709_u_load_reg_905;
wire   [7:0] select_ln1765_3_fu_630_p3;
reg   [7:0] select_ln1765_3_reg_910;
wire   [0:0] or_ln1765_2_fu_638_p2;
reg   [0:0] or_ln1765_2_reg_915;
wire   [7:0] select_ln1765_8_fu_660_p3;
reg   [7:0] select_ln1765_8_reg_922;
wire   [7:0] select_ln1765_12_fu_676_p3;
reg   [7:0] select_ln1765_12_reg_927;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] ap_phi_reg_pp0_iter0_vBarSel_3_loc_0_reg_281;
reg   [0:0] ap_phi_reg_pp0_iter1_vBarSel_3_loc_0_reg_281;
reg   [0:0] ap_phi_reg_pp0_iter2_vBarSel_3_loc_0_reg_281;
wire   [2:0] ap_phi_reg_pp0_iter0_hBarSel_5_loc_0_reg_296;
reg   [2:0] ap_phi_reg_pp0_iter1_hBarSel_5_loc_0_reg_296;
reg   [2:0] ap_phi_reg_pp0_iter2_hBarSel_5_loc_0_reg_296;
wire   [63:0] idxprom45_fu_524_p1;
wire   [63:0] idxprom47_fu_529_p1;
wire   [5:0] add_ln691_fu_422_p2;
wire   [9:0] add_ln692_fu_458_p2;
wire   [9:0] zext_ln691_fu_488_p1;
wire   [15:0] or_ln1716_fu_319_p2;
wire   [0:0] trunc_ln1716_fu_309_p1;
wire   [0:0] icmp_ln1765_fu_355_p2;
wire   [7:0] empty_fu_367_p2;
wire   [0:0] icmp_ln878_fu_393_p2;
wire   [5:0] trunc_ln878_fu_448_p1;
wire   [5:0] add_ln691_1_fu_482_p2;
wire   [3:0] or_ln_fu_504_p3;
wire   [7:0] zext_ln1748_fu_512_p1;
wire   [10:0] tmp_1_fu_516_p3;
wire   [0:0] sel_tmp5_fu_561_p2;
wire   [0:0] sel_tmp6_fu_566_p2;
wire   [0:0] xor_ln1765_fu_571_p2;
wire   [0:0] sel_tmp16_demorgan_fu_587_p2;
wire   [0:0] sel_tmp16_fu_591_p2;
wire   [0:0] and_ln1765_3_fu_597_p2;
wire   [0:0] and_ln1765_2_fu_582_p2;
wire   [0:0] and_ln1765_1_fu_576_p2;
wire  signed [7:0] val_assign_3_cast_fu_545_p1;
wire   [0:0] sel_tmp3_fu_557_p2;
wire   [0:0] or_ln1765_fu_610_p2;
wire   [7:0] select_ln1765_fu_602_p3;
wire   [7:0] select_ln1765_1_fu_616_p3;
wire   [0:0] or_ln1765_1_fu_624_p2;
wire  signed [7:0] val_assign_4_cast_fu_549_p1;
wire   [7:0] select_ln1765_5_fu_644_p3;
wire   [7:0] select_ln1765_6_fu_652_p3;
wire  signed [7:0] val_assign_5_cast_fu_553_p1;
wire   [7:0] select_ln1765_10_fu_668_p3;
wire  signed [7:0] val_assign_cast_fu_684_p1;
wire   [7:0] select_ln1765_2_fu_693_p3;
wire  signed [7:0] val_assign_1_cast_fu_687_p1;
wire   [7:0] select_ln1765_7_fu_705_p3;
wire  signed [7:0] val_assign_2_cast_fu_690_p1;
wire   [7:0] select_ln1765_11_fu_717_p3;
wire   [7:0] select_ln1765_4_fu_699_p3;
wire   [7:0] select_ln1765_9_fu_711_p3;
wire   [7:0] select_ln1765_13_fu_723_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_62;
reg    ap_condition_289;
reg    ap_condition_223;
reg    ap_condition_633;
reg    ap_condition_637;
reg    ap_condition_178;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 vBarSel_1 = 1'd0;
#0 yCount_V_1 = 6'd0;
#0 hBarSel_1 = 3'd0;
#0 xCount_V_1 = 10'd0;
end

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarArray #(
    .DataWidth( 3 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
DPtpgBarArray_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarArray_address0),
    .ce0(DPtpgBarArray_ce0),
    .q0(DPtpgBarArray_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_r #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_VESA_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_VESA_r_address0),
    .ce0(DPtpgBarSelRgb_VESA_r_ce0),
    .q0(DPtpgBarSelRgb_VESA_r_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_g #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_VESA_g_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_VESA_g_address0),
    .ce0(DPtpgBarSelRgb_VESA_g_ce0),
    .q0(DPtpgBarSelRgb_VESA_g_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_b #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_VESA_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_VESA_b_address0),
    .ce0(DPtpgBarSelRgb_VESA_b_ce0),
    .q0(DPtpgBarSelRgb_VESA_b_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_CEA_r #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_CEA_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_CEA_r_address0),
    .ce0(DPtpgBarSelRgb_CEA_r_ce0),
    .q0(DPtpgBarSelRgb_CEA_r_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_CEA_g #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_CEA_g_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_CEA_g_address0),
    .ce0(DPtpgBarSelRgb_CEA_g_ce0),
    .q0(DPtpgBarSelRgb_CEA_g_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_CEA_b #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelRgb_CEA_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelRgb_CEA_b_address0),
    .ce0(DPtpgBarSelRgb_CEA_b_ce0),
    .q0(DPtpgBarSelRgb_CEA_b_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_601_y #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_601_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_601_y_address0),
    .ce0(DPtpgBarSelYuv_601_y_ce0),
    .q0(DPtpgBarSelYuv_601_y_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_601_v #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_601_v_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_601_v_address0),
    .ce0(DPtpgBarSelYuv_601_v_ce0),
    .q0(DPtpgBarSelYuv_601_v_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_709_y #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_709_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_709_y_address0),
    .ce0(DPtpgBarSelYuv_709_y_ce0),
    .q0(DPtpgBarSelYuv_709_y_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_709_v #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_709_v_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_709_v_address0),
    .ce0(DPtpgBarSelYuv_709_v_ce0),
    .q0(DPtpgBarSelYuv_709_v_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_601_u #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_601_u_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_601_u_address0),
    .ce0(DPtpgBarSelYuv_601_u_ce0),
    .q0(DPtpgBarSelYuv_601_u_q0)
);

design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelYuv_709_u #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
DPtpgBarSelYuv_709_u_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DPtpgBarSelYuv_709_u_address0),
    .ce0(DPtpgBarSelYuv_709_u_ce0),
    .q0(DPtpgBarSelYuv_709_u_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((icmp_ln1716_fu_313_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_hBarSel_5_loc_0_reg_296 <= 3'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_hBarSel_5_loc_0_reg_296 <= ap_phi_reg_pp0_iter0_hBarSel_5_loc_0_reg_296;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((icmp_ln1716_1_fu_325_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_vBarSel_3_loc_0_reg_281 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_vBarSel_3_loc_0_reg_281 <= ap_phi_reg_pp0_iter0_vBarSel_3_loc_0_reg_281;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_289)) begin
        if (((icmp_ln878_1_fu_452_p2 == 1'd0) & (icmp_ln1716_reg_747 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_hBarSel_5_loc_0_reg_296 <= add_ln1745_fu_470_p2;
        end else if (((icmp_ln878_1_fu_452_p2 == 1'd1) & (icmp_ln1716_reg_747 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_hBarSel_5_loc_0_reg_296 <= hBarSel_1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_hBarSel_5_loc_0_reg_296 <= ap_phi_reg_pp0_iter1_hBarSel_5_loc_0_reg_296;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln1721_fu_399_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1716_1_reg_752 == 1'd0) & (icmp_ln1716_reg_747 == 1'd1))) begin
        ap_phi_reg_pp0_iter2_vBarSel_3_loc_0_reg_281 <= xor_ln1728_fu_410_p2;
    end else if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1721_fu_399_p2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1716_1_reg_752 == 1'd0)) | ((1'd0 == and_ln1721_fu_399_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1716_1_reg_752 == 1'd0) & (icmp_ln1716_reg_747 == 1'd0)))) begin
        ap_phi_reg_pp0_iter2_vBarSel_3_loc_0_reg_281 <= vBarSel_1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_vBarSel_3_loc_0_reg_281 <= ap_phi_reg_pp0_iter1_vBarSel_3_loc_0_reg_281;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((icmp_ln1716_reg_747 == 1'd1)) begin
            hBarSel_1 <= 3'd0;
        end else if (((icmp_ln878_1_fu_452_p2 == 1'd0) & (icmp_ln1716_reg_747 == 1'd0))) begin
            hBarSel_1 <= add_ln1745_fu_470_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((icmp_ln1716_1_reg_752 == 1'd1)) begin
            vBarSel_1 <= 1'd0;
        end else if ((1'b1 == ap_condition_223)) begin
            vBarSel_1 <= xor_ln1728_fu_410_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_178)) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1716_fu_313_p2 == 1'd1))) begin
            xCount_V_1 <= 10'd0;
        end else if ((1'b1 == ap_condition_637)) begin
            xCount_V_1 <= zext_ln691_fu_488_p1;
        end else if ((1'b1 == ap_condition_633)) begin
            xCount_V_1 <= add_ln692_fu_458_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1721_fu_399_p2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1716_1_reg_752 == 1'd0))) begin
        yCount_V_1 <= add_ln691_fu_422_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1716_1_fu_325_p2 == 1'd1)) | ((1'd0 == and_ln1721_fu_399_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1716_1_reg_752 == 1'd0) & (icmp_ln1716_reg_747 == 1'd1)))) begin
        yCount_V_1 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (empty_60_fu_373_p2 == 1'd1) & (1'b1 == ap_ce))) begin
        DPtpgBarSelRgb_VESA_b_load_reg_890 <= DPtpgBarSelRgb_VESA_b_q0;
        DPtpgBarSelRgb_VESA_g_load_reg_885 <= DPtpgBarSelRgb_VESA_g_q0;
        DPtpgBarSelRgb_VESA_r_load_reg_880 <= DPtpgBarSelRgb_VESA_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (empty_60_fu_373_p2 == 1'd0) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_709_u_load_reg_905 <= DPtpgBarSelYuv_709_u_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_709_v_load_reg_900 <= DPtpgBarSelYuv_709_v_q0;
        DPtpgBarSelYuv_709_y_load_reg_895 <= DPtpgBarSelYuv_709_y_q0;
        and_ln1765_reg_769_pp0_iter2_reg <= and_ln1765_reg_769_pp0_iter1_reg;
        and_ln1765_reg_769_pp0_iter3_reg <= and_ln1765_reg_769_pp0_iter2_reg;
        or_ln1765_2_reg_915 <= or_ln1765_2_fu_638_p2;
        select_ln1765_12_reg_927 <= select_ln1765_12_fu_676_p3;
        select_ln1765_3_reg_910 <= select_ln1765_3_fu_630_p3;
        select_ln1765_8_reg_922 <= select_ln1765_8_fu_660_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1765_reg_769 <= and_ln1765_fu_361_p2;
        and_ln1765_reg_769_pp0_iter1_reg <= and_ln1765_reg_769;
        icmp_ln1716_1_reg_752 <= icmp_ln1716_1_fu_325_p2;
        icmp_ln1716_reg_747 <= icmp_ln1716_fu_313_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarArray_ce0 = 1'b1;
    end else begin
        DPtpgBarArray_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelRgb_CEA_b_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_CEA_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelRgb_CEA_g_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_CEA_g_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelRgb_CEA_r_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_CEA_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelRgb_VESA_b_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_VESA_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelRgb_VESA_g_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_VESA_g_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelRgb_VESA_r_ce0 = 1'b1;
    end else begin
        DPtpgBarSelRgb_VESA_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_601_u_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_601_u_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_601_v_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_601_v_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_601_y_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_601_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_709_u_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_709_u_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_709_v_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_709_v_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        DPtpgBarSelYuv_709_y_ce0 = 1'b1;
    end else begin
        DPtpgBarSelYuv_709_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DPtpgBarArray_address0 = idxprom45_fu_524_p1;

assign DPtpgBarSelRgb_CEA_b_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelRgb_CEA_g_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelRgb_CEA_r_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelRgb_VESA_b_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelRgb_VESA_g_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelRgb_VESA_r_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelYuv_601_u_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelYuv_601_v_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelYuv_601_y_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelYuv_709_u_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelYuv_709_v_address0 = idxprom47_fu_529_p1;

assign DPtpgBarSelYuv_709_y_address0 = idxprom47_fu_529_p1;

assign add_ln1745_fu_470_p2 = (hBarSel_1 + 3'd1);

assign add_ln691_1_fu_482_p2 = (trunc_ln878_fu_448_p1 + 6'd1);

assign add_ln691_fu_422_p2 = (yCount_V_1 + 6'd1);

assign add_ln692_fu_458_p2 = ($signed(xCount_V_1) + $signed(10'd961));

assign and_ln1721_fu_399_p2 = (icmp_ln878_fu_393_p2 & icmp_ln1716_reg_747);

assign and_ln1765_1_fu_576_p2 = (xor_ln1765_fu_571_p2 & sel_tmp6_fu_566_p2);

assign and_ln1765_2_fu_582_p2 = (sel_tmp6_fu_566_p2 & and_ln1765_reg_769_pp0_iter3_reg);

assign and_ln1765_3_fu_597_p2 = (sel_tmp16_fu_591_p2 & and_ln1765_reg_769_pp0_iter3_reg);

assign and_ln1765_fu_361_p2 = (trunc_ln1716_fu_309_p1 & icmp_ln1765_fu_355_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_178 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_223 = ((1'd0 == and_ln1721_fu_399_p2) & (icmp_ln1716_1_reg_752 == 1'd0) & (icmp_ln1716_reg_747 == 1'd1));
end

always @ (*) begin
    ap_condition_289 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_62 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_633 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln878_1_fu_452_p2 == 1'd0) & (icmp_ln1716_reg_747 == 1'd0));
end

always @ (*) begin
    ap_condition_637 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln878_1_fu_452_p2 == 1'd1) & (icmp_ln1716_reg_747 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_hBarSel_5_loc_0_reg_296 = 'bx;

assign ap_phi_reg_pp0_iter0_vBarSel_3_loc_0_reg_281 = 'bx;

assign ap_return_0 = select_ln1765_4_fu_699_p3;

assign ap_return_1 = select_ln1765_9_fu_711_p3;

assign ap_return_2 = select_ln1765_13_fu_723_p3;

assign cmp106_fu_343_p2 = ((dpYUVCoef == 8'd0) ? 1'b1 : 1'b0);

assign cmp41_fu_337_p2 = ((color == 8'd0) ? 1'b1 : 1'b0);

assign empty_60_fu_373_p2 = ((empty_fu_367_p2 == 8'd0) ? 1'b1 : 1'b0);

assign empty_fu_367_p2 = (dpDynamicRange | color);

assign icmp_ln1716_1_fu_325_p2 = ((or_ln1716_fu_319_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1716_fu_313_p2 = ((x == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1765_fu_355_p2 = ((color != 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln878_1_fu_452_p2 = ((xCount_V_1 < 10'd63) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_393_p2 = ((yCount_V_1 != 6'd63) ? 1'b1 : 1'b0);

assign idxprom45_fu_524_p1 = tmp_1_fu_516_p3;

assign idxprom47_fu_529_p1 = DPtpgBarArray_q0;

assign or_ln1716_fu_319_p2 = (y | x);

assign or_ln1765_1_fu_624_p2 = (sel_tmp3_fu_557_p2 | and_ln1765_1_fu_576_p2);

assign or_ln1765_2_fu_638_p2 = (or_ln1765_fu_610_p2 | or_ln1765_1_fu_624_p2);

assign or_ln1765_fu_610_p2 = (and_ln1765_3_fu_597_p2 | and_ln1765_2_fu_582_p2);

assign or_ln_fu_504_p3 = {{ap_phi_reg_pp0_iter2_vBarSel_3_loc_0_reg_281}, {ap_phi_reg_pp0_iter2_hBarSel_5_loc_0_reg_296}};

assign sel_tmp16_demorgan_fu_587_p2 = (cmp41_fu_337_p2 | cmp106_fu_343_p2);

assign sel_tmp16_fu_591_p2 = (sel_tmp16_demorgan_fu_587_p2 ^ 1'd1);

assign sel_tmp2_fu_379_p2 = ((dpDynamicRange != 8'd0) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_557_p2 = (sel_tmp2_fu_379_p2 & cmp41_fu_337_p2);

assign sel_tmp5_fu_561_p2 = (cmp41_fu_337_p2 ^ 1'd1);

assign sel_tmp6_fu_566_p2 = (sel_tmp5_fu_561_p2 & cmp106_fu_343_p2);

assign select_ln1765_10_fu_668_p3 = ((and_ln1765_1_fu_576_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_601_v_q0 : val_assign_5_cast_fu_553_p1);

assign select_ln1765_11_fu_717_p3 = ((empty_60_fu_373_p2[0:0] == 1'b1) ? val_assign_2_cast_fu_690_p1 : DPtpgBarSelYuv_709_v_load_reg_900);

assign select_ln1765_12_fu_676_p3 = ((or_ln1765_fu_610_p2[0:0] == 1'b1) ? select_ln1765_5_fu_644_p3 : select_ln1765_10_fu_668_p3);

assign select_ln1765_13_fu_723_p3 = ((or_ln1765_2_reg_915[0:0] == 1'b1) ? select_ln1765_12_reg_927 : select_ln1765_11_fu_717_p3);

assign select_ln1765_1_fu_616_p3 = ((and_ln1765_1_fu_576_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_601_y_q0 : val_assign_3_cast_fu_545_p1);

assign select_ln1765_2_fu_693_p3 = ((empty_60_fu_373_p2[0:0] == 1'b1) ? val_assign_cast_fu_684_p1 : DPtpgBarSelYuv_709_y_load_reg_895);

assign select_ln1765_3_fu_630_p3 = ((or_ln1765_fu_610_p2[0:0] == 1'b1) ? select_ln1765_fu_602_p3 : select_ln1765_1_fu_616_p3);

assign select_ln1765_4_fu_699_p3 = ((or_ln1765_2_reg_915[0:0] == 1'b1) ? select_ln1765_3_reg_910 : select_ln1765_2_fu_693_p3);

assign select_ln1765_5_fu_644_p3 = ((and_ln1765_3_fu_597_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_709_v_q0 : DPtpgBarSelYuv_601_v_q0);

assign select_ln1765_6_fu_652_p3 = ((and_ln1765_1_fu_576_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_601_u_q0 : val_assign_4_cast_fu_549_p1);

assign select_ln1765_7_fu_705_p3 = ((empty_60_fu_373_p2[0:0] == 1'b1) ? val_assign_1_cast_fu_687_p1 : DPtpgBarSelYuv_709_u_load_reg_905);

assign select_ln1765_8_fu_660_p3 = ((or_ln1765_fu_610_p2[0:0] == 1'b1) ? select_ln1765_5_fu_644_p3 : select_ln1765_6_fu_652_p3);

assign select_ln1765_9_fu_711_p3 = ((or_ln1765_2_reg_915[0:0] == 1'b1) ? select_ln1765_8_reg_922 : select_ln1765_7_fu_705_p3);

assign select_ln1765_fu_602_p3 = ((and_ln1765_3_fu_597_p2[0:0] == 1'b1) ? DPtpgBarSelYuv_709_y_q0 : DPtpgBarSelYuv_601_y_q0);

assign tmp_1_fu_516_p3 = {{3'd0}, {zext_ln1748_fu_512_p1}};

assign trunc_ln1716_fu_309_p1 = x[0:0];

assign trunc_ln878_fu_448_p1 = xCount_V_1[5:0];

assign val_assign_1_cast_fu_687_p1 = $signed(DPtpgBarSelRgb_VESA_g_load_reg_885);

assign val_assign_2_cast_fu_690_p1 = $signed(DPtpgBarSelRgb_VESA_b_load_reg_890);

assign val_assign_3_cast_fu_545_p1 = $signed(DPtpgBarSelRgb_CEA_r_q0);

assign val_assign_4_cast_fu_549_p1 = $signed(DPtpgBarSelRgb_CEA_g_q0);

assign val_assign_5_cast_fu_553_p1 = $signed(DPtpgBarSelRgb_CEA_b_q0);

assign val_assign_cast_fu_684_p1 = $signed(DPtpgBarSelRgb_VESA_r_load_reg_880);

assign xor_ln1728_fu_410_p2 = (vBarSel_1 ^ 1'd1);

assign xor_ln1765_fu_571_p2 = (1'd1 ^ and_ln1765_reg_769_pp0_iter3_reg);

assign zext_ln1748_fu_512_p1 = or_ln_fu_504_p3;

assign zext_ln691_fu_488_p1 = add_ln691_1_fu_482_p2;

endmodule //design_1_v_tpg_0_0_tpgPatternDPColorSquare
